### ISSUE TITLE
Fusion360 3rd-party add-ins still possible?

### ISSUE THREAD

**Issue by SEIZMICdesign** [WilkoV/Fusion360_ExportIt#37]
I can't figure out how I would go about loading a third-party add-in now. I've done it once before, but it seems Autodesk has eliminated this functionality now.

**Comment by WilkoV** [comment]
Download the ExportIt.zip file from https://github.com/WilkoV/Fusion360_ExportIt/releases/tag/0.9.0, unpack it to a folder you like and follow the installation steps I've outlined here. https://github.com/WilkoV/Fusion360_ExportIt/tree/0.9.0#installation
Let me know if it worked for you.

**Comment by WilkoV** [comment]
Closed because no feedback. I guess the problem is solved.
