### ISSUE TITLE
v1.0.0 has bad deliverables/ExportIt.tar.gz

### ISSUE THREAD

**Issue by rdamazio** [WilkoV/Fusion360_ExportIt#40]
It seems the latest release is fine in .zip format, but in .tar.gz format, the bundled deliverables/ExportIt.tar.gz file is truncated. (Do you even need that file in the release?)

From attempting to extract it:

```
...
x ./apper/docs/source/_static/addin_dialog.png: truncated gzip input
tar: Error exit delayed from previous errors.
```

**Comment by rdamazio** [comment]
(to be clear: this is the .tar.gz that goes inside the .tar.gz)

**Comment by rdamazio** [comment]
Ah, maybe you need a ` --exclude="deliberables` / `-x "deliverables/*"` in createExportItDeliverable.bash ?

**Comment by WilkoV** [comment]
Oh - I never noticed that. I guess I've to check my deliver script. I'm unsure if I need this. I had Apple users in mind for this.

**Comment by rdamazio** [comment]
I'm an Apple user, in case you need me to test anything. I just deleted the deliverables directory from my installed add-in, and everything seems to still be working.
